# Generated by Django 4.2 on 2023-05-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_finished_alter_quiz_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='finished',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Успешно пройден'),
        ),
    ]
