# Generated by Django 4.2 on 2025-05-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_quizresult_quiz_alter_quizresult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
