# Generated by Django 4.2 on 2025-05-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_quizresult_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
