# Generated by Django 4.2 on 2025-05-14 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_quizresult_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 11, 49, 42, 940207, tzinfo=datetime.timezone.utc)),
        ),
    ]
