# Generated by Django 4.2 on 2025-05-14 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_quizresult_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
