# Generated by Django 4.2 on 2023-04-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=1, upload_to='users/'),
            preserve_default=False,
        ),
    ]
