# Generated by Django 4.2 on 2023-04-28 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_course_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='content',
        ),
    ]
